### ISSUE TITLE
Create new process and inject

### ISSUE THREAD

**Issue by htdag** [kubo/injector#12]
Currently injector only support inject library to existing process.
So, possible to create new process (suspend) and inject?

Also support set parameter and environment from command line.

**Comment by kubo** [comment]
> Currently injector only support inject library to existing process.
> So, possible to create new process (suspend) and inject?

On linux, [`LD_PRELOAD`](https://en.wikipedia.org/wiki/DLL_injection#Approaches_on_Unix-like_systems) is absolutely better than this.
```c
  pid_t pid = fork();
  if (pid == 0) {
    // child process
    setenv("LD_PRELOAD", path_to_shared_library, 1);
    exec(...); // or any function of exec() family
```

On Windows, use [`CreateProcess`][] with [`CREATE_SUSPENDED`] instead of `OpenProcess` [here](https://github.com/kubo/injector/blob/fc7794f78f6540befe2c4be3c9a97e8298be08a1/src/windows/injector.c#L462). I don't know whether `injector_inject()` works against suspended processes. 

[`CreateProcess`]: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa
[`CREATE_SUSPENDED`]: https://docs.microsoft.com/en-us/windows/win32/procthread/process-creation-flags#CREATE_SUSPENDED

> Also support set parameter and environment from command line.

How about reading a file in the directory where the injected file exists?
1. Get the full path of the injected file. ([dladdr][] on linux, [DllMain][] and [GetModuleFileName] on windows)
2. Strip the last part to get the directory name.
3. Add a fixed file name to the directory name and read parameters in the file.

[dladdr]: https://man7.org/linux/man-pages/man3/dladdr.3.html
[DllMain]: https://docs.microsoft.com/en-us/windows/win32/dlls/dllmain
[GetModuleFileName]: https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamew
