### ISSUE TITLE
Trace/breakpoint trap on UserLAnd (Android App)

### ISSUE THREAD

**Issue by TheOiseth** [kubo/injector#17]
I installed UserLand (v2.7.3) on my android phone, lxde desktop. Target process after injection fails with an error "Trace/breakpoint trap". Arch: aarch64, linux kernel version 3.18.71

**Comment by kubo** [comment]
Though I don't have Android suitable to run UserLAnd and I have not investigated it, I guest that injector doesn't work on it.
That's because:
1. UserLAnd uses PRoot to trap system calls.
2. [PRoot](https://proot-me.github.io/) uses ptrace.
3. Injector also uses ptrace.
4. Only one process can trace a process. However two processes try to trace the target process. I guess that injector lose.

If [this issue](https://github.com/CypherpunkArmory/UserLAnd/issues/1078#issuecomment-787073985) is fixed, injector would work. Otherwise, it doesn't.
