### ISSUE TITLE
ubuntu 18.04 inject snap process failed

### ISSUE THREAD

**Issue by nightlight89** [kubo/injector#21]
failed to open /usr/lib/x86_64-linux-gnu/libc-2.31.so.(error: No such file or directory).

sudo snap install libreoffice

**Comment by fr0zenrain** [comment]
my platform is chrooted process aarch64, when i inject to a chrooted running process,i have similar issue,dlopen failed  libhook.so No such file or directory

**Comment by kubo** [comment]
@nightlight89 The issue itself will be fixed by 66436cb898374b601844f39a695afdec76bb6541, which checks libc files in `/snap/core*/*` also. However injection may fail by other reasons because snap processes are protected by security policies.

@fr0zenrain Your issue is not related to this. Could you create a new one with a [minimal reproducible example].

[minimal reproducible example]: https://en.wikipedia.org/wiki/Minimal_reproducible_example
