### ISSUE TITLE
Wine?

### ISSUE THREAD

**Issue by Witherking25** [kubo/injector#28]
could this be used to inject dlls into a wine process?

**Comment by kubo** [comment]
No, I couldn't.

I guess that this can inject linux shared libraries though they cannot call functions compiled for Windows.

**Comment by vap0rwaves** [comment]
Above he mentions injecting a dll into a wine process, so that should actually be possible with this library.
I just was working on this oddly, and got my dll injected into an exe running in wine environment.

So firstly things outside this library which you need to do:
You must spawn the process yourself so you have permissions for. If you spawn the process then try to dynamically inject to the target process you will not be able to find the process in your environment. Your injector should issue a spawn command (CreateProcess msdn) and use that handle.

I haven't had time to specifically test this injector library in wine, but my simple loadlibrary create remote thread injection is working. So given this works on windows it should just work in wine. Just a couple hoops to jump through

**Comment by Witherking25** [comment]
I've been making a dll inject decky loader plugin, so I'll probably end up wrapping things with a custom steam compatibility tool

**Comment by kubo** [comment]
As far as I checked, it  works on Wine. Wine seems to provide special mechanism to enable `CreateRemoteThread`.

In README.md:

> [Wine](https://www.winehq.org/) (on Linux x86_64):
>
> injector process \ target process | x64 | x86
> -- | -- | --
> x64 | 😃 success | 💀  failure
> x86 | 💀  failure | 😃 success
