### ISSUE TITLE
Don't work on some windows pc.

### ISSUE THREAD

**Issue by huhuang03** [kubo/injector#3]
Same code, on two pc, one work and one not. 
The error msg from `injector_error()` is:
```
LoadLibrary in the target process failed: Invalid access to memory location.
```
What's the maybe reason..

**Comment by kubo** [comment]
Could you check the DLL to be injected. As far as I googled, LoadLibrary returns the error [ERROR_NOACCESS](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--500-999-#ERROR_NOACCESS) when a DLL could not be loaded by access violation. (See [here](https://www.gamedev.net/forums/topic/552198-loadlibrary-998-error_noaccess/4551438/))

Otherwise, could you post a sample program which causes the error.

**Comment by huhuang03** [comment]
Thanks for your reply. After some research. I found that the issue is the injected dll has a dependency on `msvcxxx.dll`, which may not exist on some pc. After some modify remove the `msvcxxx.dll` dependency. It works.
